### ISSUE TITLE
Update node to v20 warning

### ISSUE THREAD

**Issue by biodranik** [irgaly/xcode-cache#57]
@irgaly hi! Why we see the [following warning](https://github.com/organicmaps/organicmaps/actions/runs/8554587840) in our actions, and how to resolve it?

```
 Build iOS (Debug)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: irgaly/xcode-cache@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

```

**Comment by irgaly** [comment]
Thank you for your feedback!

I have migrated xcode-cache to use node20 runtime, and released it as [v1.7.2](https://github.com/irgaly/xcode-cache/releases/tag/v1.7.2).
`xcode-cache@v1` will automatically point v1.7.2, so please re-run your workflow and check the warning has been disappeared.
